version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/gpc-analysis-extension"
      - "/selenium-optmeowt-crawler"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      # Groups for Version Updates
      crawler-minor-and-patch:
        update-types:
          - minor
          - patch
      crawler-major:
        update-types:
          - major

      # Groups for Security Updates
      crawler-security-minor-and-patch:
        applies-to: security-updates
        update-types:
          - minor
          - patch
      crawler-security-major:
        applies-to: security-updates
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
