version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      crawler-minor-and-patch:
        update-types:
          - minor
          - patch
      crawler-minor-and-patch:
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
