
services:
  crawl_driver:
    build: 
      context: ./selenium-optmeowt-crawler
    image: ghcr.io/privacy-tech-lab/crawl-driver:latest
    ports:
      - "5901:5901"
      - "6901:6901"
    environment:
      - DEBUG_MODE=${DEBUG_MODE}
      - TEST_CRAWL=${TEST_CRAWL}
      - CRAWL_ID=${CRAWL_ID}
      - MARIADB_ROOT_PASSWORD=toor
      - TIMESTAMP=${TIMESTAMP}
    user: "0"
    volumes:
      - ./crawl_results:/srv/analysis/selenium-optmeowt-crawler/crawl_results      
    networks:
      - mariadb_network
    depends_on:
      mariadb:
        condition: service_healthy
      rest_api:
        condition: service_healthy
      crawl_browser:
        condition: service_started

  well_known_crawl:
    build: 
      context: ./well-known-crawl
    image: ghcr.io/privacy-tech-lab/well-known-crawl:latest
    environment:
      - TEST_CRAWL=${TEST_CRAWL}
      - CRAWL_ID=${CRAWL_ID}
      - TIMESTAMP=${TIMESTAMP}
    user: "0"
    volumes:
      - ./crawl_results:/crawl_results   
      - ./selenium-optmeowt-crawler/crawl-sets:/crawl-sets   
    networks:
      - mariadb_network
    depends_on:
      crawl_driver:
        condition: service_completed_successfully

  rest_api:
    build: 
      context: ./rest_api
    image: ghcr.io/privacy-tech-lab/rest-api:latest
    ports:
      - "8080:8080"
    environment:
      - DEBUG_MODE=${DEBUG_MODE}
      - MARIADB_ROOT_PASSWORD=toor
      - DB_HOST=mariadb
      - DB_CONNECTION=mysql
      - DB_DATABASE=analysis
      - DB_USERNAME=root
      - DB_PASSWORD=toor
    networks:
      - mariadb_network
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://rest_api:8080/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure


  mariadb:
    build:
      context: ./mariadb-compose
    image: ghcr.io/privacy-tech-lab/mariadb-custom:latest
    container_name: mariadb-compose
    environment:
      - DB_CONNECTION=mysql
      - DB_DATABASE=analysis
      - DB_USERNAME=root
      - MARIADB_ROOT_PASSWORD=toor
    ports:
      - "3306:3306"
    networks:
      - mariadb_network
    healthcheck:
        test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-ptoor"]
        interval: 5s
        timeout: 3s
        retries: 10
        start_period: 30s
    restart: unless-stopped


        
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
      - MARIADB_ROOT_PASSWORD=toor
    networks:
      - mariadb_network
    depends_on:
      mariadb:
        condition: service_healthy
  
  crawl_browser:
    image: selenium/standalone-firefox:nightly
    privileged: true
    ports:
      - "4444:4444"
###Delete the following lines to start the crawler with the VNC environment started
    environment:
     - SE_START_VNC=false
    volumes:
      - ./selenium-optmeowt-crawler/ff-optmeowt-2.0.1.xpi:/extensions/ff-optmeowt-2.0.1.xpi
    networks:
      - mariadb_network
    shm_size: 2g
    
volumes:
  mariadb:
    driver: local


networks:
  mariadb_network:
    driver: bridge
