#### adapted from JS code from this library: https://www.npmjs.com/package/@iabgpp/cmpapi

TcfCaV1Field = {} 
TcfCaV1Field["VERSION"] = "Version"
TcfCaV1Field["CREATED"] = "Created"
TcfCaV1Field["LAST_UPDATED"] = "LastUpdated"
TcfCaV1Field["CMP_ID"] = "CmpId"
TcfCaV1Field["CMP_VERSION"] = "CmpVersion"
TcfCaV1Field["CONSENT_SCREEN"] = "ConsentScreen"
TcfCaV1Field["CONSENT_LANGUAGE"] = "ConsentLanguage"
TcfCaV1Field["VENDOR_LIST_VERSION"] = "VendorListVersion"
TcfCaV1Field["TCF_POLICY_VERSION"] = "TcfPolicyVersion"
TcfCaV1Field["USE_NON_STANDARD_STACKS"] = "UseNonStandardStacks"
TcfCaV1Field["SPECIAL_FEATURE_EXPRESS_CONSENT"] = "SpecialFeatureExpressConsent"
TcfCaV1Field["PURPOSES_EXPRESS_CONSENT"] = "PurposesExpressConsent"
TcfCaV1Field["PURPOSES_IMPLIED_CONSENT"] = "PurposesImpliedConsent"
TcfCaV1Field["VENDOR_EXPRESS_CONSENT"] = "VendorExpressConsent"
TcfCaV1Field["VENDOR_IMPLIED_CONSENT"] = "VendorImpliedConsent"
TcfCaV1Field["SEGMENT_TYPE"] = "SegmentType"
TcfCaV1Field["PUB_PURPOSES_EXPRESS_CONSENT"] = "PubPurposesExpressConsent"
TcfCaV1Field["PUB_PURPOSES_IMPLIED_CONSENT"] = "PubPurposesImpliedConsent"
TcfCaV1Field["NUM_CUSTOM_PURPOSES"] = "NumCustomPurposes"
TcfCaV1Field["CUSTOM_PURPOSES_EXPRESS_CONSENT"] = "CustomPurposesExpressConsent"
TcfCaV1Field["CUSTOM_PURPOSES_IMPLIED_CONSENT"] = "CustomPurposesImpliedConsent"
